### ISSUE TITLE
libdoc: Please add a functionality to create a libdoc for several ressource documents

### ISSUE THREAD

**Issue by alexhaller** [robotframework/MavenPlugin#28]
Hi,

we have many ressource files (about 20) for which we want to create a libdoc. In my opinion it is not possible to create for all files the libdoc at once. So please add a parameter for the libdoc functionality such as "ressourcePath".

Thanks a lot!

Best regards,
Alex

**Comment by diakula** [comment]
I also find this helpful to have! I now end up writing multiple libdoc sections in the configurations for each Java class.

**Comment by jussimalinen** [comment]
This would be useful for sure. Unless someone requests this from inside Nokia, I dont think we will have time to implement this anytime soon though. Pull requests are welcome!

**Comment by diakula** [comment]
Hi guys, I played with the idea, see here: https://github.com/diakula/MavenPlugin/commit/7f11b659700a022ec25748684f929544d33708f0

Basically, I changed the semantic of <libraryOrResourceFile> tag so it could accept ant-like patterns (same implement as what maven uses).

Before:
<libraryOrResourceFile>${basedir}/src/main/java/bla/XmlUtilitiesLibrary.java</libraryOrResourceFile>
After:
<libraryOrResourceFile>${basedir}/src/main/java/**/*.java</libraryOrResourceFile>

Can someone look at my branch, if the approach looks sound?

**Comment by jussimalinen** [comment]
Sorry for the delay, I have been quite busy lately. The solution is quite complex, but if it works I'm ready to include it. It would be a great addition to maven plugin!

I would however prefer shorter and less complex methods in a pull request. If you could try to clean the code up to shorter more specialized helper methods, it would make it easier to do a code review.

Thanks!

**Comment by diakula** [comment]
Thanks for the feedback. Regarding the readability of the changes - I tried to keep the changes to existing files to the minimum. All new code went to new files. Below I give a small walkthrough summary for the intended changes, a bit better structured than the commit message:

Changes to original files:
- pom.xml - added a dependency to the reflections library that harvests source/resource/class names.
- LibDocMojo - made the call to libdoc from single to multiple - 1 after the other. The LibDocConfiguration supplies the collection of different parameters, instead of a parameters set.
- LibDocConfiguration - biggest change - added harvesting of resources from the classpath by checking for patterns in the order of source file (*.java), classes, resources (*.py included). All code in separate harvesters classes. 

Added unit tests for harvesters.

I hope this helps.

**Comment by jussimalinen** [comment]
Thanks. If you could make a pull request for this with a slightly cleaned up code (especially shorter methods), I could include this into the distribution!

**Comment by diakula** [comment]
Ok, I'll do some more extensive testing and cleanup first.

**Comment by diakula** [comment]
Ok, finished testing, result in https://github.com/robotframework/MavenPlugin/pull/34 .

**Comment by diakula** [comment]
Any news whether we can get the libdoc and the testdoc enhancements for multiple sources in any time soon?

**Comment by jussimalinen** [comment]
Sorry, we have been very busy making the RF 3.0 release. Once we get that out, I should have some free time.

**Comment by shamaho** [comment]
What's the current status on this? it's a most valuable feature !

**Comment by YK1434** [comment]
Any update on this pleaseeee

**Comment by simplyviks** [comment]
was this implemented?

**Comment by phearme** [comment]
since this is not yet implemented, I opened the sources of a generated html doc created with libdoc and noticed the keywords, documentation and arguments are all in the `libdoc` javascript variable. a solution would be to generate a doc file for each resource, and then merge all `libdoc` variables into one, and then generate a new doc file based on the same template and replace the js variable with the merged one. it's a hack but maybe can work.

**Comment by rfabbris** [comment]
Not sure this is the best way to do it but I managed to run `libdoc` on multiple files in a pom.
Below my code:
`			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-antrun-plugin</artifactId>
				<version>1.8</version>
				<executions>
					<execution>
						<phase>package</phase>
						<configuration>
							<target>
								<fileset id="my-fileset" dir="src/main/resources/resources/" />
								<pathconvert targetos="unix" pathsep="," property="my-file-list" refid="my-fileset">
									<map from="${project.basedir}\src\main\resources\resources\" to="" />
								</pathconvert>
								<echo file="${project.basedir}\target\Resources.txt">${my-file-list}</echo>
							</target>
						</configuration>
						<goals>
							<goal>run</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.codehaus.gmaven</groupId>
				<artifactId>gmaven-plugin</artifactId>
				<version>1.4</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>execute</goal>
						</goals>
						<configuration>
							<properties>
								<resource_file>${project.basedir}\target\Resources.txt</resource_file>
							</properties>
							<source>
							def file = new File(project.properties.resource_file)
							project.properties.resource_content = file.getText().replace(".robot", "")
							</source>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>com.soebes.maven.plugins</groupId>
				<artifactId>iterator-maven-plugin</artifactId>
				<version>0.5.0</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>iterator</goal>
						</goals>
						<configuration>
							<content>${resource_content}</content>
							<pluginExecutors>
								<pluginExecutor>
									<plugin>
										<groupId>org.robotframework</groupId>
										<artifactId>robotframework-maven-plugin</artifactId>
										<version>1.4.7</version>
									</plugin>
									<goal>libdoc</goal>
									<configuration>
										<libdoc>
											
											<libraryOrResourceFile>src/main/resources/resources/@item@.robot</libraryOrResourceFile>
											<outputFile>@item@.html</outputFile>
										</libdoc>
									</configuration>
								</pluginExecutor>
							</pluginExecutors>
						</configuration>
					</execution>
				</executions>
			</plugin>`
