### ISSUE TITLE
Import of 'requests' library fails with org.robotframework maven plugin but succeeds with jybot at command line

### ISSUE THREAD

**Issue by bdfariello** [robotframework/MavenPlugin#32]
Hi,

I'm trying to import the 'requests' library in one of my Python libraries, and doing this seems to break when executing the tests using Robot Framework:

[ ERROR ] Error in file '/Users/benfariello/VMTurbo/automation/com.vmturbo.test.integration/src/test/sandbox/01_python_experimenting.txt': Importing test library 'main.libraries.sandbox.PythonTestLibrary' failed: SyntaxError: mismatched input 'as' expecting COLON (connectionpool.py, line 342)

However, they succeed when running from the OSX command line using "jybot <test directory>"

For reference, jybot --version returns "Robot Framework 2.8.6 (Jython 2.7b4 on java1.7.0_67)", so I added these as dependencies in the pom.xml file.

**Comment by bdfariello** [comment]
My suspicion is that the plugin is using Jython 2.5 and not Jython 2.7b4. Is there a way to override this behavior? I tried placing a dependency on jython 2.7-b4 in my pom file but it didn't work. It would be nice to be able to set the version of Jython that the org.robotframework maven plugin is using internally.

**Comment by jussimalinen** [comment]
Plugin uses the standalone version from maven, which currently includes jython 2.5. The next robot version (2.9) will start using jython 2.7, so this will be fixed by then.

I'm not sure how to workaround this easily meanwhile... You could make your own version of robot standalone jar with jython2.7 and then use that jar either locally or from your own repository? Not too tempting.

**Comment by bdfariello** [comment]
Cool, thanks. I see 2.9 alpha 1 was released on April 10th, so at this point it's probably going to be simpler to wait for 2.9 GA. Thanks!
